### PR TITLE
update Chinese

### PR DESCRIPTION
**Pull request by feroooooo**
Update the Chinese translation, thanks 尾御池 in mcmod(a Chinese website).

BTW, I found it there is some hard-coding language in the code, like 389 and 405 line in CommonUtils.java file. This relates the pickupmode hint shown in the button of screen.
```java
translatable("dankstorage.mode." + PickupMode.VALUES[ordinal].name()), true);
```
If possible, hope you can use translation key instead of directly the name of enum variables. Maybe create a map like {enumname:translation key} can help.

### CODE REVIEW

**Comment by Tfarcenim** [comment]
These lines already have translation keys though, the enum is used there so it's easier to manage
https://github.com/Tfarcenim/Dank-Storage/blob/1.20.1-multiloader/common/src/main/resources/assets/dankstorage/lang/en_us.json#L24-L27

**Comment by feroooooo** [comment]
> These lines already have translation keys though, the enum is used there so it's easier to manage https://github.com/Tfarcenim/Dank-Storage/blob/1.20.1-multiloader/common/src/main/resources/assets/dankstorage/lang/en_us.json#L24-L27

Sorry, I dont realized that is translations keys yet, maybe the problem is somewhere else. Here is the place cant be translated by lang file.

**Comment by Tfarcenim** [comment]
Added translation for HUD text, this should be complete now

**Comment by feroooooo** [comment]
> Added translation for HUD text, this should be complete now

thanks for your work

**Pull request merged**
